name: .NET Framework Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Runs the job on Windows server
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the repository content for use in the workflow
    
    - name: Set up .NET Framework 4.0
      uses: microsoft/setup-msbuild@v1  # Installs MSBuild
      with:
        msbuild-version: '16.8'

    - name: Restore NuGet packages
      run: nuget restore PopulationReportingSystem.sln

    - name: Build with MSBuild
      run: msbuild /p:Configuration=Release PopulationReportingSystem.sln

    - name: Run Tests (if any)
      run: |
        # This command assumes you have tests to run. Adjust as needed.
        # Example command to run unit tests:
        # vstest.console.exe path\to\test\project.dll
        echo "Running tests"
    
    - name: Publish the application
      run: msbuild /p:Configuration=Release /p:PublishDir=./publish PopulationReportingSystem.sln

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: ./publish  # Path where the build output (EXE/DLL) is stored

